export const NAME_INPUT_DEFECT = 'NAME_INPUT_DEFECT'
export const CODE_INPUT_DEFECT = 'CODE_INPUT_DEFECT'
export const INJECTION_INPUT_DEFECT = 'INJECTION_INPUT_DEFECT'

export const CLEAN_INPUTS_DEFECT = 'CLEAN_INPUTS_DEFECT'
export const SELECT_INPUTS_DEFECT = 'SELECT_INPUTS_DEFECT'
