export const DATE_INPUT_INGOING = 'DATE_INPUT_INGOING'
export const SPARE_INPUT_INGOING = 'SPARE_INPUT_INGOING'
export const QUANTITY_INPUT_INGOING = 'QUANTITY_INPUT_INGOING'
export const ORIGIN_INPUT_INGOING = 'ORIGIN_INPUT_INGOING'
export const PROVIDER_INPUT_INGOING = 'PROVIDER_INPUT_INGOING'
export const PRICE_INPUT_INGOING = 'PRICE_INPUT_INGOING'

export const CLEAN_INPUTS_INGOING = 'CLEAN_INPUTS_INGOING'
export const SELECT_INPUTS_INGOING = 'SELECT_INPUTS_INGOING'
