export const NAME_INPUT_USER = 'NAME_INPUT_USER'
export const PASSWORD_INPUT_USER = 'PASSWORD_INPUT_USER'
export const LEVEL_INPUT_USER = 'LEVEL_INPUT_USER'

export const CLEAN_INPUTS_USER = 'CLEAN_INPUTS_USER'
export const SELECT_INPUTS_USER = 'SELECT_INPUTS_USER'
