export const MOLDE_INPUT_SHOT = 'MAOLDE_INPUT_SHOT'
export const DATE_INPUT_SHOT = 'DATE_INPUT_SHOT'
export const SHIFT_INPUT_SHOT = 'SHIFT_INPUT_SHOT'
export const COMMENTS_INPUT_SHOT = 'COMMENTS_INPUT_SHOT'

export const CLEAN_INPUTS_SHOT = 'CLEAN_INPUTS_SHOT'
