export const NAME_INPUT_ISSUE = 'NAME_INPUT_ISSUE'
export const CODE_INPUT_ISSUE = 'CODE_INPUT_ISSUE'

export const CLEAN_INPUTS_ISSUE = 'CLEAN_INPUTS_ISSUE'
export const SELECT_INPUTS_ISSUE = 'SELECT_INPUTS_ISSUE'
