export const MACHINE_INPUT_PROGRAM = 'MACHINE_INPUT_PROGRAM'
export const MOLDE_INPUT_MPROGRAM = 'MOLDE_INPUT_PROGRAM'
export const MODEL_INPUT_PROGRAM = 'MODEL_INPUT_PROGRAM'
export const TIME_INPUT_PROGRAM = 'TIME_INPUT_PROGRAM'
export const CAPACITY_INPUT_PROGRAM = 'CAPACITY_INPUT_PROGRAM'
export const CYCLES_INPUT_PROGRAM = 'CYCLES_INPUT_PROGRAM'

export const CLEAN_INPUTS_PROGRAM = 'CLEAN_INPUTS_PROGRAM'
export const SELECT_INPUTS_PROGRAM = 'SELECT_INPUTS_PROGRAM'
