export const CODE_INPUT_LOCATION = 'CODE_INPUT_LOCATION'
export const NAME_INPUT_LOCATION = 'NAME_INPUT_LOCATION'
export const AREA_INPUT_LOCATION = 'AREA_INPUT_LOCATION'

export const CLEAN_INPUTS_LOCATION = 'CLEAN_INPUTS_LOCATION'
export const SELECT_INPUTS_LOCATION = 'SELECT_INPUTS_LOCATION'
