export const NUMBER_INPUT_MACHINE = 'NUMBER_INPUT_ISSUE'
export const SERIAL_INPUT_MACHINE = 'SERIAL_INPUT_ISSUE'
export const CLOSING_INPUT_MACHINE = 'CLOSING_INPUT_ISSUE'
export const SPINDLE_INPUT_MACHINE = 'SPINDLE_INPUT_ISSUE'

export const CLEAN_INPUTS_MACHINE = 'CLEAN_INPUTS_MACHINE'
export const SELECT_INPUTS_MACHINE = 'SELECT_INPUTS_MACHINE'
