export const PERIOD_PRODUCTION = 'PERIOD_PRODUCTION'
export const SHIFT_PRODUCTION = 'SHIFT_PRODUCTION'
export const FILTER_PRODUCTION = 'FILTER_PRODUCTION'

export const DATE_PRODUCTION = 'DATE_PRODUCTION'
export const BACK_PRODUCTION = 'BACK_PRODUCTION'
export const FORWARD_PRODUCTION = 'FORWARD_PRODUCTION'
