export const NUMBER_INPUT_MODEL = 'NUMBER_INPUT_MODEL'
export const NAME_INPUT_MODEL = 'NAME_INPUT_MODEL'
export const FAMILY_INPUT_MODEL = 'FAMILY_INPUT_MODEL'

export const CLEAN_INPUTS_MODEL = 'CLEAN_INPUTS_MODEL'
